const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const C=require('../prototype/controls.js');
const root=path.join(__dirname,'../prototype');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(8795,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH});const page=await browser.newPage({viewport:{width:375,height:667},isMobile:true,hasTouch:true});let dialog='';let failures=[];page.on('pageerror',e=>failures.push(e.message));page.on('dialog',d=>d.accept(dialog));await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',r=>r.fulfill({path:process.env.SUPABASE_JS,contentType:'application/javascript'}));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:process.env.LOCAL_FONTS?fs.readFileSync(path.join(process.env.LOCAL_FONTS,'inter.local.css'),'utf8').replaceAll('url(', 'url(http://127.0.0.1:8795/'):'',contentType:'text/css'}));await page.route('http://127.0.0.1:8795/*.woff2',r=>r.fulfill({path:path.join(process.env.LOCAL_FONTS,path.basename(new URL(r.request().url()).pathname)),contentType:'font/woff2'}));await page.goto('http://127.0.0.1:8795/?demo');await page.waitForSelector('.tabs');
let count=0;async function check(name,fn){await fn();count++;console.log('PASS '+name);}
async function ready(){await page.evaluate(()=>{const d=dealById('dm1'),C=DealControls;d.params._trust={version:2,buyer:{},seller:{},funds:{how:{v:C.bankMethods[0]}}};for(const side of ['buyer','seller'])for(const[k,,must]of C.verification[side].items)if(must)d.params._trust[side][k]={by:'Chris'};d.params._payment_security={type:'escrow',confirmed:true,reference:'SPA lot 1'};window._docs=[];window._atts=[];for(const doc of C.criticalDocs){window._docs.push({deal_id:d.id,doc,status:['ncnda','imfpa','spa'].includes(doc)?'signed':'received',att_id:doc});window._atts.push({id:doc,target_type:'deal',target_id:d.id,path:doc+'.pdf'});}render();});}
// Keep fresh-page setup independent from app initializer naming.
const reset=async()=>{await page.reload();await page.waitForSelector('.tabs');await page.evaluate(()=>{const d=dealById('dm1');d.status='Active';d.params._trust={version:2,buyer:{},seller:{},funds:{}};delete d.params._payment_security;window._docs=[];window._atts=[];for(const s of stepsOf(d.id))s.status='open';goView('deals');render();});};
try{
await reset();
await check('all eight mineral loading codes blocked without security',async()=>{assert.equal(await page.evaluate(()=>['v2.13','8.1','8.2','10.1','10.2','10.3','10.4','10.5'].every(code=>DealControls.stepMissing(dealById('dm1'),{code},controlState()).length>0)),true);});
await check('no file: document cannot close itself or follow-up',async()=>{dialog='';await page.evaluate(async()=>{const d=dealById('dm1');await setDoc(d,'ncnda','requested');await setDoc(d,'ncnda','signed');});assert.equal(await page.evaluate(()=>docRow('dm1','ncnda').status),'requested');assert.equal(await page.evaluate(()=>stepsOf('dm1').find(s=>DealControls.key(s)==='ncnda').status),'open');});
await check('document override requires reason and writes history',async()=>{dialog='Attorney retains signed original';await page.evaluate(()=>setDoc(dealById('dm1'),'ncnda','signed'));assert.equal(await page.evaluate(()=>docRow('dm1','ncnda').override_reason),dialog);assert.ok(await page.evaluate(()=>window._hist.some(x=>x.field==='control:document:ncnda'&&x.new_value==='Attorney retains signed original')));});
await check('red flag enters Review Required, cancellation retains it, reason clears and logs it',async()=>{await page.evaluate(()=>{const d=dealById('dm1');d.params._trust.flags={docs:{by:'Chris'}};openDealPage(d.id);goView('deal');dealTab[d.id]='steps';openKeys.add('+trust:'+d.id);render();});assert.equal(await page.evaluate(()=>controlStatus(dealById('dm1'))),'Review Required');dialog='';await page.evaluate(()=>document.querySelector('[data-trust="dm1:flags:docs"]').click());await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>DealControls.flags(dealById('dm1')).length));dialog='Original independently confirmed';await page.evaluate(()=>document.querySelector('[data-trust="dm1:flags:docs"]').click());await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>DealControls.flags(dealById('dm1')).length),0);assert.ok(await page.evaluate(()=>window._hist.some(x=>x.field==='control:flag_clear:docs')));});
await ready();
await check('AI cannot complete an insecure loading step',async()=>{assert.match(await page.evaluate(async()=>{const d=dealById('dm1'),s=stepsOf(d.id).find(s=>DealControls.key(s)==='delivery');delete d.params._payment_security;try{await runAct({change:'tick_step',target_type:'deal',target_id:d.id,step_id:s.id,step:s.title});return 'unexpected success';}catch(e){return e.message;}}),/Payment Secured/);await ready();});
await check('step override requires a reason, logs it, and does not release loading',async()=>{dialog='';const id=await page.evaluate(()=>{const s=stepsOf('dm1').find(s=>DealControls.key(s)==='spa');s.status='open';window._docs=window._docs.filter(r=>r.doc!=='spa');return s.id;});assert.equal(await page.evaluate(id=>controlStepOverride(dealById('dm1'),stepsOf('dm1').find(s=>s.id===id),''),id),false);assert.equal(await page.evaluate(id=>controlStepOverride(dealById('dm1'),stepsOf('dm1').find(s=>s.id===id),'Attorney records exception pending contract copy'),id),true);assert.ok(await page.evaluate(()=>window._hist.some(x=>x.field.startsWith('control:step:'))));assert.ok(await page.evaluate(()=>DealControls.loadingMissing(dealById('dm1'),controlState()).length));await ready();});
await check('both verification presentations report the same must-have result',async()=>{assert.equal(await page.evaluate(()=>GATES.every(g=>gateState(dealById('dm1'),g).ok===DealControls.verified(dealById('dm1'),g.side,controlState()).ok)),true);});
await check('Funds phone choices switch correctly inside the modal hit areas',async()=>{await page.evaluate(()=>openGate('dm1','funds'));await page.locator('#flowDlg [data-gfund="dm1:3"]').click();assert.equal(await page.evaluate(()=>gateState(dealById('dm1'),GATES[2]).ok),false);await page.locator('#flowDlg [data-gfund="dm1:0"]').click();assert.equal(await page.evaluate(()=>gateState(dealById('dm1'),GATES[2]).ok),true);await page.evaluate(()=>flClose());});
await check('LOI/ICPO/FCO alternative outcomes close from accepted SPA without rigid order',async()=>{await page.evaluate(()=>leanTickFromDoc(dealById('dm1'),'spa','SPA signed'));assert.equal(await page.evaluate(()=>leanSteps(dealById('dm1'),stepsOf('dm1')).filter(s=>['intent','offer'].includes(DealControls.key(s))).every(s=>s.status==='done')),true);});
await check('custom label displays while immutable code keeps its safety gate',async()=>{assert.equal(await page.evaluate(()=>{const d=dealById('dm1'),s=stepsOf(d.id).find(x=>DealControls.key(x)==='spa');s.title=s.custom_label='Our contract wording';window._docs=window._docs.filter(x=>x.doc!=='assay');return leanSteps(d,stepsOf(d.id)).find(x=>x.id===s.id).title==='Our contract wording'&&stepGateMissing(d,s.id).length>0;}),true);});
await check('Won cancelled without reason; explicit reason is recorded',async()=>{dialog='';assert.equal(await page.evaluate(()=>controlWon(dealById('dm1'))),false);assert.equal(await page.evaluate(()=>dealById('dm1').status),'Active');dialog='Owner approved archive pending commission';assert.equal(await page.evaluate(()=>controlWon(dealById('dm1'))),true);assert.ok(await page.evaluate(()=>window._hist.some(x=>x.field==='control:won_override'&&x.new_value==='Owner approved archive pending commission')));});
await reset();await ready();
await check('loading panel cannot save an insecure mineral load',async()=>{await page.evaluate(()=>{const d=dealById('dm1');delete d.params._payment_security;openDealPage(d.id);goView('deal');dealTab[d.id]='steps';render();document.querySelector('[data-ldnew]').click();});await page.fill('[data-ldf="t_loaded"]','34');await page.locator('[data-ldsave]').click();assert.equal(await page.evaluate(()=>loadsOf('dm1').length),0);});
await check('mobile controls have invisible 44px hit boxes',async()=>{assert.equal(await page.evaluate(()=>[...document.querySelectorAll('button,a[href],summary')].filter(b=>b.getBoundingClientRect().width).every(b=>{const h=b.querySelector('db-hit').getBoundingClientRect();return h.width>=44&&h.height>=44;})),true);});
await ready();await page.evaluate(()=>{goView('deals');render();const t=document.getElementById('toast');if(t)t.style.visibility='hidden';});await page.waitForTimeout(300);fs.mkdirSync(path.join(__dirname,'../docs/review'),{recursive:true});await page.screenshot({path:path.join(__dirname,'../docs/review/mobile.png'),fullPage:true});await page.evaluate(()=>{openDealPage('dm1');goView('deal');dealTab.dm1='steps';openKeys.add('+trust:dm1');render();});await page.locator('[data-security=type]').locator('xpath=ancestor::div[contains(@class,"trow")]').screenshot({path:path.join(__dirname,'../docs/review/security.png')});await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{goView('deals');render();});await page.screenshot({path:path.join(__dirname,'../docs/review/desktop.png'),fullPage:true});
assert.deepEqual(failures,[]);console.log(`${count} browser regression checks PASS; no page errors`);
}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
