// Isolated PostgreSQL engine. Never connects to Supabase or production data.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {PGlite}=require(process.env.PGLITE_PATH||'@electric-sql/pglite');
const C=require('../prototype/controls.js');
const did='00000000-0000-0000-0000-000000000001';
const schema=`create role anon; create role authenticated;
create function is_owner() returns boolean language sql as $$select coalesce(current_setting('test.owner',true),'true')='true'$$;
create function current_actor() returns text language sql as $$select 'Test Owner'::text$$;
create table deals(id uuid primary key default gen_random_uuid(),kind text,status text default 'Active',params jsonb default '{}',updated_at timestamptz,updated_by text);
create table deal_steps(id uuid primary key default gen_random_uuid(),deal_id uuid references deals,code text,stage text,sort int,title text,status text default 'open',custom boolean default false,evidence text,done_by text,done_at timestamptz);
create table kit_templates(kind text,code text,title text);
create table attachments(id uuid primary key default gen_random_uuid(),target_type text,target_id text,path text);
create table deal_docs(id uuid primary key default gen_random_uuid(),deal_id uuid references deals,doc text,status text,att_id uuid references attachments,expires_on date,updated_by text,updated_at timestamptz,unique(deal_id,doc));
create table loads(id uuid primary key default gen_random_uuid(),deal_id uuid references deals,t_loaded numeric);
create table events(id bigserial primary key,deal_id uuid,field text,old_value text,new_value text,changed_by text,source text);
create function set_step(p_id uuid,p_status text,p_evidence text default null) returns void language plpgsql security definer as $$begin if not is_owner() then raise exception 'not allowed';end if;update deal_steps set status=p_status,evidence=p_evidence where id=p_id;end$$;
create function save_deal(p_id uuid,p_status text) returns void language plpgsql security definer as $$begin if not is_owner() then raise exception 'not allowed';end if;update deals set status=p_status where id=p_id;end$$;
`;
async function db(){const db=new PGlite();await db.exec(schema);await db.exec(`insert into deals(id,kind) values('${did}','mineral');insert into deal_steps(deal_id,code,title,status) values('${did}','v2.14','Seller paid','done'),('${did}','v2.15','Commission paid','done');`);const file=fs.readdirSync(path.join(__dirname,'../supabase/migrations')).find(x=>x.endsWith('_v17_mineral_controls.sql'));await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',file),'utf8'));return db;}
async function ready(db){const params={_trust:{version:2,buyer:{},seller:{},funds:{how:{v:C.bankMethods[0]}}},_payment_security:{type:'escrow',confirmed:true,reference:'SPA lot 1'}};for(const side of ['buyer','seller'])for(const[k,,must]of C.verification[side].items)if(must)params._trust[side][k]={by:'Chris'};await db.query('update deals set params=$1 where id=$2',[params,did]);for(const doc of C.criticalDocs){const a=await db.query("insert into attachments(target_type,target_id,path) values('deal',$1,$2) returning id",[did,doc+'.pdf']);await db.query('insert into deal_docs(deal_id,doc,status,att_id) values($1,$2,$3,$4)',[did,doc,['ncnda','imfpa','spa'].includes(doc)?'signed':'received',a.rows[0].id]);}return params;}
async function step(db,code){return(await db.query("insert into deal_steps(deal_id,code,title) values($1,$2,'Custom wording') returning id",[did,code])).rows[0].id;}
async function deny(db,sql,args,match){await assert.rejects(db.query(sql,args),match);}
test('migration executes and preserves historical paid ticks; security is seeded open',async()=>{const d=await db();const r=await d.query('select code,status from deal_steps');assert.equal(r.rows.length,3);assert.equal(r.rows.find(x=>x.code==='v2.18').status,'open');assert.equal(r.rows.find(x=>x.code==='v2.14').status,'done');await d.close();});
test('database controls and overrides',async t=>{const d=await db();
 await t.test('raw load insert and legacy Won RPC fail closed',async()=>{await deny(d,'insert into loads(deal_id,t_loaded) values($1,34)',[did],/Loading blocked/);await deny(d,"select save_deal($1,'Won')",[did],/Won blocked/);});
 await t.test('blank document, step and closure override reasons rejected',async()=>{await deny(d,"select control_document_override($1,'spa','signed',' ')",[did],/reason/);await deny(d,"select control_step_override((select id from deal_steps limit 1),' ')",[],/reason/);await deny(d,"select control_close_deal($1,' ')",[did],/Won blocked/);});
 await t.test('missing documents cannot be marked received',async()=>{for(const doc of C.criticalDocs)await deny(d,'insert into deal_docs(deal_id,doc,status) values($1,$2,$3)',[did,doc,'received'],/needs a file/);});
 await t.test('security and loading cannot be skipped',async()=>{for(const code of ['v2.18','7.1','7.2','v2.13','8.1','8.2','10.1','10.2','10.3','10.4','10.5']){const id=code==='v2.18'?(await d.query("select id from deal_steps where code='v2.18'")).rows[0].id:await step(d,code);await deny(d,"select control_step_override($1,'test reason')",[id],/cannot be skipped/);await deny(d,"select set_step($1,'done')",[id],/Payment Secured/);}});
 await ready(d);
 await t.test('attached document still needs an explicit reason to become Not needed',async()=>{await deny(d,"update deal_docs set status='na' where doc='spa'",[],/recorded override/);});
 await t.test('anon has no control RPC execution privilege',async()=>{await d.exec('set role anon');await deny(d,"select control_close_deal($1,'reason')",[did],/permission denied/);await d.exec('reset role');});
 await t.test('complete security permits loads, and edited labels retain identity',async()=>{await d.query('insert into loads(deal_id,t_loaded) values($1,34)',[did]);const id=await step(d,'6.7');await d.query("update deal_steps set title='Renamed SPA' where id=$1",[id]);await d.query("select set_step($1,'done')",[id]);await deny(d,"update deal_steps set code='free' where id=$1",[id],/immutable/);await deny(d,"update deal_steps set id=gen_random_uuid() where id=$1",[id],/immutable/);});
 await t.test('red flag blocks critical steps and requires fresh clearance reason',async()=>{await d.query(`update deals set params=jsonb_set(params,'{_trust,flags}','{"docs":{"by":"Chris"}}') where id=$1`,[did]);await deny(d,'insert into loads(deal_id,t_loaded) values($1,34)',[did],/Review Required/);const id=await step(d,'v2.12');await deny(d,"select set_step($1,'done')",[id],/Review Required/);await deny(d,"update deals set params=jsonb_set(params,'{_trust,flags}','{}') where id=$1",[did],/new reason/);await d.query(`update deals set params=jsonb_set(jsonb_set(params,'{_trust,flags}','{}'),'{_trust,clearances}','{"docs":{"reason":"Bank independently validated original","on":"2026-10-03"}}') where id=$1`,[did]);assert.ok((await d.query("select * from events where field='control:flag_clear:docs'")).rows.length);});
 await t.test('evidence override is audited; security evidence override cannot release loading',async()=>{await d.query("update deal_docs set att_id=null,status='draft' where doc='security'");await d.query("select control_document_override($1,'security','received','Original held by attorney')",[did]);await deny(d,'insert into loads(deal_id,t_loaded) values($1,34)',[did],/Payment Secured/);assert.ok((await d.query("select * from events where field='control:document:security'")).rows.length);});
 await t.test('deliberate Won override recorded with blockers',async()=>{await d.query("select control_close_deal($1,'Owner accepts unresolved settlement for archive')",[did]);assert.match((await d.query("select new_value from events where field='control:won_override'")).rows[0].new_value,/Payment Secured/);});
 await t.test('non-owner cannot use any override RPC',async()=>{await d.exec("set test.owner='false'");for(const q of ["select control_close_deal($1,'reason')","select control_document_override($1,'spa','signed','reason')"])await deny(d,q,[did],/not allowed/);await d.exec("set test.owner='true'");});
 await d.close();});
