// SA deal kit v1 (sa1) – generated from kit.py / guide.py. Same content as the kit_templates table.
window.KIT = {
 "routes": {"local": "Local sale by truck (FOT / FCA / DAP)", "bulk": "Export by sea – bulk ship (FOB / CFR / CIF)", "container": "Export in containers (FCA / CPT / CIP)", "road": "Export by road to a neighbouring country (FCA / DAP)"},
 "guide": {
  "local": {
   "terms": [
    "Write every term as '[term] [named place] Incoterms 2020'.",
    "FOT is common in SA but is not an Incoterm. Write 'FCA [plant, address] Incoterms 2020', or define FOT in the SPA: who loads, whose weighbridge counts, when risk and title pass.",
    "FCA / FOT: the buyer books the trucks and carries freight (about R1,000/t Rustenburg–Durban in 2023), transit loss and seizure risk.",
    "DAP buyer's yard: the seller books the trucks and carries transit risk. Write 'DAP … tipped at buyer's stockpile' (or use DPU) and say which weighbridge counts.",
    "Avoid EXW and DDP for local deals."
   ],
   "tests": [
    "Assay 1 – before the SPA: the buyer's inspector samples the stockpile, sealed splits (step 5.2).",
    "Trial – the buyer samples and weighs on delivery and pays on the result (step 8.1).",
    "Assay 2 – at loading: the inspector samples each lot; trucks weighed in and out at both ends (step 10.1).",
    "Assay 3 – results swapped: average if within the splitting limit, umpire lab if outside (step 10.5).",
    "Standards: chrome ISO 6153 / 6154, manganese ISO 4296-1 / -2. Lab accredited by SANAS (ISO 17025)."
   ]
  },
  "bulk": {
   "terms": [
    "FOB [port]: the seller clears export and loads; the buyer books the ship and pays freight. Risk passes when the cargo is on board. Bulk ships only.",
    "CFR [destination port]: the seller also books and pays the freight. Risk still passes on board at the SA port, so the buyer insures.",
    "CIF: CFR plus insurance bought by the seller – at least ICC (C) at 110% of the price.",
    "'FOB' from a seller with no exporter code, clearing agent or terminal space is a red flag. So is 'FOB – loading at the mine'.",
    "CIF with '100% payment after discharge assay' is open-account risk for the seller."
   ],
   "tests": [
    "Assay 1 – before the SPA: the buyer's inspector samples the stockpile (step 5.2).",
    "Before loading – TML test done within 6 months and moisture test sampled no more than 7 days before loading; retest after rain (step 9.7).",
    "Assay 2 – during loading: stream sampling plus initial and final draft survey (step 10.2). Certificates in about 48 hours (step 10.4).",
    "Assay 3 – results swapped; umpire only if outside the splitting limit (step 10.5).",
    "Assay 4 – after discharge: CIQ / CCIC results in China if the SPA uses them, 2–6 weeks after discharge (step 11.3)."
   ]
  },
  "container": {
   "terms": [
    "Use FCA (container depot or terminal), CPT or CIP. FOB and CIF are for bulk ships, not containers.",
    "CIP needs ICC (A) 'all risks' cover at 110%.",
    "Give the shipping line a VGM. A 20-foot container carries about 25–27 t."
   ],
   "tests": [
    "Assay 1 – before the SPA: the buyer's inspector samples the stock (step 5.2).",
    "Assay 2 – at stuffing: sampled as the containers are packed; weights and VGM recorded (step 10.3).",
    "Certificates in about 48 hours (step 10.4). Assay 3 – results swapped, umpire if needed (step 10.5).",
    "Assay 4 – after discharge: destination results if the SPA uses them (step 11.3)."
   ]
  },
  "road": {
   "terms": [
    "FCA [plant]: the seller clears SA export and hands over to the buyer's truck; the buyer handles transit and import.",
    "DAP [buyer's site, city, country]: the seller books the trucks and carries transit risk; the buyer clears import.",
    "Avoid EXW (the buyer would become the SA exporter) and DDP (the seller would clear import abroad).",
    "SADC buyers: a SADC certificate of origin can cut the import duty (step 9.13)."
   ],
   "tests": [
    "Assay 1 – before the SPA: the buyer's inspector samples the stockpile (step 5.2).",
    "Assay 2 – at loading: each truck lot sampled; trucks weighed at both ends (step 10.1).",
    "Certificates in about 48 hours (step 10.4). Assay 3 – results swapped, umpire if needed (step 10.5)."
   ]
  }
 },
 "watch": [
  "No mining right in the seller's name, and no supply agreement with the holder.",
  "A prospecting right or a small mining permit offered for big monthly tonnages.",
  "Wash plant without environmental authorisation or water use licence.",
  "Night loading, no delivery notes, no weighbridge tickets.",
  "Only the seller's own lab certificate; the buyer's inspector is refused.",
  "Up-front 'sampling', 'truck', 'mandate' or 'inspection' fees.",
  "MT103 / MT199 / MT799 'pre-advice', RWA letters or leased SBLCs offered as payment security.",
  "Screenshot 'proof of funds', or a buyer who wants the seller to load first without escrow or LC.",
  "Bank account changed mid-deal, or the account name differs from the company.",
  "Seller refuses a legal-origin warranty and chain-of-custody papers."
 ],
 "watchExport": [
  "'FOB Richards Bay/Durban' from someone with no exporter code, clearing agent or terminal space.",
  "Chrome concentrate declared as Group C, or moisture certificates older than 7 days or from a rapid meter.",
  "Someone charging a fee to 'arrange the ITAC chrome permit' – no permit system is in force (25 Sep 2026)."
 ],
 "stages": {"mineral": ["1. Enquiry (day 0–3)", "2. Protect our commission (before names)", "3. KYC checks (day 1–10)", "4. Offers (day 3–10)", "5. Proof of product – first assay (day 5–15)", "6. Contract – SPA (day 10–30)", "7. Payment security (before loading)", "8. Trial", "9. Logistics and paperwork", "10. Loading – sampling and weighing", "11. Documents and payment", "12. Commission and close"], "transport": ["1. Qualify", "2. Paperwork", "3. Terms", "4. Checks", "5. Agreements", "6. Trial load", "7. Running", "8. Close-out"]},
 "tpl": {
  "mineral": [
   ["1.1", "1. Enquiry (day 0–3)", ["local", "bulk", "container", "road"], "Buyer's requirement written down", "Product (UG2 concentrate, lumpy, ROM or manganese lumpy). Spec with min, max and rejection limits. Tonnes for the trial and per month. Incoterm plus named place. Price idea, currency, VAT in or out, per DMT or WMT. Payment instrument, start date and the buyer's inspector.", "Us, with the buyer", "Requirement sheet or signed LOI"],
   ["1.2", "1. Enquiry (day 0–3)", ["local", "bulk", "container", "road"], "Order makes physical sense (tonnes, trucks, route)", "Tonnes match the seller's plant and mining-title capacity. A 34 t side tipper means 1,000 t is about 30 loads. For export, the route and port (Maputo, Durban, Richards Bay) are realistic.", "Us", "Note in the deal file"],
   ["1.3", "1. Enquiry (day 0–3)", ["local", "bulk", "container", "road"], "Principals named: who signs the SPA and who pays", "We know which company signs the sale contract and which company pays. Everyone else in the chain is written down as an intermediary (Deal terms: seller chain, buyer chain).", "Us", "Principals written in Deal terms"],
   ["1.4", "1. Enquiry (day 0–3)", ["local", "bulk", "container", "road"], "NCNDA signed with each side before names are shared", "Signed by an authorised signatory of the principal, not only by another broker. Names the parties being introduced, runs for a set term (often 5 years), South African law. E-signatures are valid (ECTA). A template 'governed by ICC 500/600' is recycled boilerplate – those are letter-of-credit rules.", "Us and the seller; us and the buyer", "Signed NCNDA in Files"],
   ["2.1", "2. Protect our commission (before names)", ["local", "bulk", "container", "road"], "Commission agreement signed by the party who pays", "Rate (usually R30–R50 per DMT). How DMT is worked out: inspector's weight and moisture certificates, or weighbridge tonnes × (1 − moisture %). Payable only on paid and delivered tonnes, within e.g. 7 working days of the seller being paid. How it is paid (escrow split, paymaster or EFT). Covers repeat orders and affiliates. Non-circumvention, VAT, SA law. Signed by a director with proof of authority. Base it on the ICC model contract E837E, not internet IMFPA templates.", "Us and the seller (and/or the buyer)", "Signed agreement + signing authority"],
   ["2.2", "2. Protect our commission (before names)", ["local", "bulk", "container", "road"], "Principals acknowledge us in writing", "An intermediary clause in the SPA, or a signed acknowledgement or irrevocable payment instruction from the seller naming us.", "Seller and buyer", "Clause or signed letter"],
   ["2.3", "2. Protect our commission (before names)", ["local"], "Our commission set up as a split in escrow (TradeSafe)", "If TradeSafe is used, add us as the agent when the transaction is created, so our share is paid automatically when the funds are released to the seller.", "Us, when the escrow is created", "TradeSafe transaction showing our split"],
   ["3.1", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Both companies checked on CIPC", "Registration number and active status. Directors match the people signing. A company registered a few weeks ago that claims 'ROM from our own mine' is a red flag.", "Us", "CIPC printout in Files"],
   ["3.2", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Mining right or permit verified", "Get a copy with its DMPR reference, then check it: a certified copy from the regional MPTRO office (R100) or the DMPR licensing map. Holder, mineral (chrome or manganese), area and dates must match the seller's story. A prospecting right may only sell bulk samples, with the Minister's written permission. A mining permit covers at most 5 ha – too small for big monthly tonnages.", "Us or the buyer's due-diligence team", "Title copy + our check note"],
   ["3.3", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Chain of custody proven (if the seller is not the right holder)", "For a trader, wash plant or tailings operator: signed supply agreement with the right holder; recent delivery notes and weighbridge tickets from the source; for a wash plant, its environmental authorisation (NEMA) and water use licence; a stock ownership or release letter. Tick 'Not needed' only if the seller holds the right itself.", "Seller provides; we check", "Chain-of-custody pack in Files"],
   ["3.4", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Tax compliance (TCS PIN) verified on SARS eFiling", "The seller (and an SA buyer) gives a TCS PIN. We check it on eFiling on the day – it shows compliant or not at that moment. Capture the VAT number.", "Us", "TCS result saved"],
   ["3.5", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Bank letter: account in the seller's company name", "Bank-stamped confirmation letter. Phone the bank to confirm where possible. Any later change of bank account, or an account name that differs from the company, is a stop sign (payment diversion).", "Seller and its bank", "Bank letter in Files"],
   ["3.6", "3. KYC checks (day 1–10)", ["bulk", "container", "road"], "Seller can export: SARS exporter code and clearing agent", "Under FOB, CFR, CIF or FCA the seller is the exporter. It needs SARS customs registration (RLA on eFiling), an appointed clearing agent, a route and terminal, and ideally past bills of lading. 'FOB Richards Bay' quoted by someone with none of this is a red flag.", "Seller", "Exporter code + agent name"],
   ["3.7", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Buyer's proof of funds (only after the LOI)", "One of: a bank letter addressed to the seller, an escrow deposit, or a draft LC from a real bank. A screenshot or an unaddressed letter is not proof of funds. For a local buyer, also the offloading site and its weighbridge.", "Buyer", "Proof-of-funds document"],
   ["3.8", "3. KYC checks (day 1–10)", ["local", "bulk", "container", "road"], "Adverse media and sanctions search done", "Search the company names, people, phone numbers and email domains. Free-mail addresses (gmail etc.) on 'own mine' offers are a warning.", "Us", "Note on file"],
   ["3.9", "3. KYC checks (day 1–10)", ["local"], "B-BBEE affidavit or certificate (only if the buyer asks)", "Not a legal requirement for a private sale. Small firms (turnover under R10m) use a sworn affidavit or CIPC certificate.", "Seller", "Affidavit or certificate"],
   ["4.1", "4. Offers (day 3–10)", ["local", "bulk", "container", "road"], "Buyer's LOI or ICPO received", "Signed on letterhead: spec, tonnes, Incoterm and named place, price or formula, payment instrument, inspection company and a short validity. Many real mines and traders skip this and go quote → KYC → contract; that is fine.", "Buyer", "Signed LOI or ICPO"],
   ["4.2", "4. Offers (day 3–10)", ["local", "bulk", "container", "road"], "Seller's FCO received", "Spec as typical and guaranteed, with min/max and rejection limits (Cr2O3, Cr:Fe, SiO2, moisture, size). Tonnes per month, price per DMT or WMT (say which), named place, loading capacity per day, inspection, payment and validity. Signed by the right holder or its authorised offtaker.", "Seller", "Signed FCO"],
   ["4.3", "4. Offers (day 3–10)", ["local", "bulk", "container", "road"], "Both sides on the same terms", "Same price unit (DMT or WMT), currency, VAT in or out, Incoterm plus named place ('FCA Mooinooi plant, Incoterms 2020') and the same inspection company. Write them in Deal terms.", "Us", "Term sheet agreed by email"],
   ["5.1", "5. Proof of product – first assay (day 5–15)", ["local", "bulk", "container", "road"], "Site visit: stockpile, loader and weighbridge seen", "The buyer or its representative, with us, at the named plant. Date- and GPS-stamped video showing the stockpile, a loader and a weighbridge able to load trucks.", "Buyer, us and seller", "Visit report + video in Files"],
   ["5.2", "5. Proof of product – first assay (day 5–15)", ["local", "bulk", "container", "road"], "Assay 1 – buyer's inspector samples the stock (sealed splits)", "WHEN: before the SPA. The buyer's inspector takes the samples, not the seller (SGS, Mitra SK, Cotecna, Alex Stewart, Intertek or BV). Sealed splits for seller, buyer and reserve. Accredited lab (SANAS / ISO 17025). Compare with the FCO. The buyer usually pays. Lab results in about 48 hours (Mitra SK). Never rely on the seller's own certificate; SGS checks its own certificates for free. A stockpile grab sample is indicative only.", "Inspector appointed by the buyer", "Sampling report + COA in Files"],
   ["5.3", "5. Proof of product – first assay (day 5–15)", ["local", "bulk", "container", "road"], "Quantity and ownership of the stock confirmed", "Stockpile survey or inspection by the inspector, plus an ownership or release letter from the seller.", "Inspector and seller", "Survey + ownership letter"],
   ["6.1", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA: spec, price adjustments and rejection", "UG2 chrome index spec: Cr2O3 42% basis / 40% min, Cr:Fe 1.2 min, SiO2 6% max, size ≤1 mm 95%. Local buyers often ask Cr:Fe 1.40 min and SiO2 5% max. Manganese index: Mn 36.5% basis, moisture max 12%, lump 5.5–75 mm, priced in US$ per dry tonne unit (dmtu). Price moves pro-rata per 1% Cr2O3 (or Mn unit) between min and basis; penalty per 1% SiO2 over max; buyer may reject below min.", "Seller drafts, buyer reviews, we coordinate", "Clauses in the agreed draft"],
   ["6.2", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA: which weight and which assay count", "Weight: local = certified loading weighbridge with a tolerance against the delivery weighbridge; export bulk = draft survey. Named inspector and ISO sampling standards (chrome ISO 6153/6154, manganese ISO 4296-1/-2). Where the final result is set (loading or discharge). Sealed splits and how long they are kept. Splitting limit (suggest 0.3–0.5% Cr2O3), umpire lab and who pays it. DMT = wet tonnes × (1 − moisture).", "Seller and buyer", "Clauses in the agreed draft"],
   ["6.3", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA: payment, title and risk", "Payment instrument, the documents that trigger payment, provisional and final percentages, bank charges. Title passes on payment; risk passes per the Incoterm. Incoterms do not decide title or payment – the SPA must.", "Seller and buyer", "Clauses in the agreed draft"],
   ["6.4", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA: legal-origin warranty and papers with every load", "Seller warrants legal origin, states the mining-right number, sends chain-of-custody papers with each load and gives an audit right. A seller who refuses this is a stop sign – illegal chrome is being laundered through wash plants and traders.", "Seller", "Clause in the agreed draft"],
   ["6.5", "6. Contract – SPA (day 10–30)", ["bulk", "container", "road"], "SPA: change-in-law clause (ITAC permit, export tax, quota)", "On 25 Sep 2026 no chrome export permit or export tax is in force, but it could be gazetted at short notice. Agree who carries a permit delay or tax cost, and when either side may cancel.", "Seller and buyer", "Clause in the agreed draft"],
   ["6.6", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA: delivery plan, force majeure, disputes, our clause", "Local: trucks per day. Export: laycan, loading rate, demurrage. Force majeure for Transnet rail and port, borders and weather (payment excluded). Governing law and arbitration, anti-bribery, sanctions, and the clause acknowledging us.", "Seller and buyer", "Clauses in the agreed draft"],
   ["6.7", "6. Contract – SPA (day 10–30)", ["local", "bulk", "container", "road"], "SPA signed by both principals", "Authorised signatories on both sides; e-signature is fine.", "Seller and buyer", "Signed SPA in Files"],
   ["7.1", "7. Payment security (before loading)", ["local"], "Buyer funds escrow (or pays before each batch)", "The buyer deposits the first lot into TradeSafe; the seller gets a letter of comfort before loading. Alternative: TT before each batch ('test, pay, load'). TradeSafe fee: 0.45% (R1–5m), 0.35% (R5–10m), 0.25% (over R10m).", "Buyer", "Letter of comfort or proof of payment"],
   ["7.2", "7. Payment security (before loading)", ["bulk", "container", "road"], "LC issued and checked before loading", "Irrevocable LC (MT700) from the buyer's bank, advised and ideally confirmed by an SA bank. The seller checks every document the LC asks for against the SPA and gets amendments before loading. Allow 1–3 weeks.", "Buyer's bank, then seller's bank", "LC advice from the seller's bank"],
   ["7.3", "7. Payment security (before loading)", ["local", "bulk", "container", "road"], "No fake payment security accepted", "MT103 copies, MT199/MT799 'pre-advice', RWA letters, 'bank-to-bank' promises and leased SBLCs are not payment security. An SBLC (MT760) is only a backstop if the buyer defaults, not a way of paying. Never pay up-front 'fees' to anyone in the chain.", "Us, seller and buyer", "Note: instrument checked"],
   ["8.1", "8. Trial", ["local"], "Trial: 1–3 trucks, weighed and sampled on delivery, then paid", "The buyer samples and weighs at delivery and pays on the result. Scale up only after the trial is paid.", "Seller, buyer and transporter", "Delivery ticket, buyer's COA, payment proof"],
   ["8.2", "8. Trial", ["bulk", "container", "road"], "First export lot fully inspected", "The full loading inspection runs even on a trial or first container batch.", "Seller and inspector", "Inspector's certificates"],
   ["9.1", "9. Logistics and paperwork", ["local", "bulk", "container", "road"], "Trucks booked (FOT/FCA: buyer · DAP: seller · export: seller to port)", "Roadworthy trucks with goods-in-transit cover (one Rustenburg–Durban chrome contract required R500k). Price guide: about R1,020/t Rustenburg–Durban (705 km) in 2023 – check current rates.", "Whoever the Incoterm says", "Transport order or rate confirmation"],
   ["9.2", "9. Logistics and paperwork", ["local", "bulk", "container", "road"], "Every truck papered", "Weighbridge ticket, and a delivery note showing the source right holder or plant, truck registration, driver, and seal or sample number. Copies of the title and supply papers in the cab. Undocumented loads can be seized and the trucks forfeited (seven trucks forfeited in 2026).", "Seller and transporter", "Ticket + delivery note per truck"],
   ["9.3", "9. Logistics and paperwork", ["bulk", "container", "road"], "Export customs: clearing agent lodges the SAD500 with SARS", "The exporter of record (the seller under FCA, FOB, CFR, CIF) has its clearing agent lodge the export declaration (SAD500 / CCD) by EDI. Avoid EXW for export – it makes the foreign buyer the SA exporter.", "Seller and clearing agent", "SARS customs release"],
   ["9.4", "9. Logistics and paperwork", ["bulk", "container", "road"], "Chrome: ITAC permit position checked before shipping", "25 Sep 2026: no chrome export permit or export tax in force – draft Notice 6712 only. Check ITAC's gazette list before each shipment. Manganese has no export-control proposal. Anyone selling an 'ITAC permit' service for a fee is a red flag. Tick 'Not needed' for manganese.", "Seller", "Note with the check date"],
   ["9.5", "9. Logistics and paperwork", ["bulk"], "Terminal space and stack dates booked", "TPT Richards Bay or Durban, or MPDC / Grindrod at Maputo. Trucks are called forward to match the vessel. Durban vessel queue was about 4 days in July 2026.", "Seller or its forwarder", "Terminal booking confirmation"],
   ["9.6", "9. Logistics and paperwork", ["bulk"], "Vessel nominated (FOB: buyer · CFR/CIF: seller)", "Laycan, loading rate and demurrage come from the SPA.", "Buyer (FOB) or seller (CFR, CIF)", "Vessel nomination accepted"],
   ["9.7", "9. Logistics and paperwork", ["bulk"], "Test before loading – moisture (≤7 days) and TML (≤6 months)", "WHEN: before the ship loads. The shipper gives the master a TML test done within 6 months and a moisture test sampled no more than 7 days before loading (retest after heavy rain). Treat chrome concentrate as Group A (can liquefy). Rapid moisture meters are not good enough.", "Seller and inspector", "TML and moisture certificates + cargo declaration"],
   ["9.8", "9. Logistics and paperwork", ["bulk", "container"], "Certificate of origin (if the buyer or LC asks)", "Non-preferential certificate from a chamber of commerce (e.g. Durban Chamber). China, India and the UAE have no trade agreement with SA, so no preferential form applies.", "Seller", "Certificate of origin"],
   ["9.9", "9. Logistics and paperwork", ["bulk", "container"], "Cargo insurance at 110% (CIF / CIP only)", "CIF bulk: at least Institute Cargo Clauses (C). CIP containers: (A) 'all risks'. Tick 'Not needed' for FOB, CFR or FCA.", "Seller", "Insurance certificate"],
   ["9.10", "9. Logistics and paperwork", ["bulk"], "Maputo road leg: SeW declaration and border papers", "Only if shipping through Maputo by road: SA export clearance plus Mozambique's Single Electronic Window (SeW) declaration, agents on both sides. Truck carries invoice, packing list, waybill, cross-border permit and insurance. Lebombo takes 4–8 hours normally, 12–24+ at peaks. Tick 'Not needed' if not via Maputo.", "Seller, transporter and agents", "Border clearance records"],
   ["9.11", "9. Logistics and paperwork", ["container"], "Containers: FCA/CPT/CIP terms and VGM given to the line", "Use FCA, CPT or CIP, not FOB or CIF. Give the shipping line a SOLAS verified gross mass (VGM). A 20-foot container carries about 25–27 t.", "Seller", "VGM + booking confirmation"],
   ["9.12", "9. Logistics and paperwork", ["road"], "Cross-border permit (C-BRTA) for each truck", "The haulier needs a C-BRTA cross-border permit for the countries crossed; drivers need a PrDP. Check before the first load.", "Transporter", "Permit copies in Files"],
   ["9.13", "9. Logistics and paperwork", ["road"], "SADC certificate of origin with each load", "For buyers in SADC countries (e.g. Zambia, Zimbabwe): a SADC certificate of origin (Form CO) can cut the buyer's import duty to little or nothing. The exporter must be registered for SADC origin with SARS. Ask the clearing agent.", "Seller and clearing agent", "SADC certificate per load"],
   ["9.14", "9. Logistics and paperwork", ["road"], "Transit and import clearance arranged", "Agents at each border; transit bond where needed (e.g. Zambia via ASYCUDA). Truck carries commercial invoice, packing list, road waybill, SAD500, certificate of origin and permits. The buyer clears import under FCA or DAP.", "Seller, buyer and agents", "Border clearance records"],
   ["10.1", "10. Loading – sampling and weighing", ["local", "road"], "Assay 2 – inspector samples each lot at loading; trucks weighed both ends", "WHEN: as the trucks load. The inspector samples each lot at the plant, and/or the buyer samples at its yard – the SPA says which result is final and whether trucks are paid per lot. Weigh in and out at loading and at delivery.", "Inspector, seller and buyer", "COA + weighbridge tickets"],
   ["10.2", "10. Loading – sampling and weighing", ["bulk"], "Assay 2 – stream sampling and draft survey at the port", "WHEN: during vessel loading. The inspector samples the moving stream (ISO 6153 chrome / ISO 4296-1 manganese). Initial and final draft surveys give the bill-of-lading tonnes (about 0.5% accuracy).", "Inspector", "COA, weight and moisture certificates, draft survey"],
   ["10.3", "10. Loading – sampling and weighing", ["container"], "Assay 2 – sampling at stuffing; container weights recorded", "WHEN: as the containers are packed. Weighbridge weights plus the VGM.", "Inspector", "COA + weight list"],
   ["10.4", "10. Loading – sampling and weighing", ["bulk", "container", "road"], "Loading certificates issued (about 48 hours)", "Certificate of sampling, COA, certificate of weight (or draft survey) and moisture certificate. These go to the bank under the LC.", "Inspector", "Certificates in Files"],
   ["10.5", "10. Loading – sampling and weighing", ["local", "bulk", "container", "road"], "Assay 3 – results swapped; umpire only if outside the limit", "Each lab tests its sealed split and the results are swapped at the same time. Within the splitting limit: the average is final. Outside: the reserve sample goes to the umpire lab, and the umpire result is usually averaged with the closer party's result. Keep reserve samples 90 days to 6 months.", "Labs, seller and buyer", "Result exchange or umpire report"],
   ["11.1", "11. Documents and payment", ["local"], "Tax invoice with 15% VAT, delivery note, ticket and COA", "Local sales carry 15% VAT. The seller may zero-rate only if it exports the goods itself with documents within 90 days.", "Seller", "Tax invoice + delivery papers"],
   ["11.2", "11. Documents and payment", ["bulk", "container", "road"], "Documents presented to the bank within 21 days of shipment", "Provisional invoice, on-board bills of lading (or road waybill), COA, certificate of weight or draft survey, certificate of origin, packing list, insurance (CIF/CIP). The bank has up to 5 banking days to check them.", "Seller and its bank", "Payment under the LC"],
   ["11.3", "11. Documents and payment", ["bulk", "container"], "Assay 4 – discharge results and final invoice", "WHEN: after discharge, if the SPA uses discharge-port results (e.g. CIQ/CCIC in China) – usually 2–6 weeks after discharge. The balance is paid or refunded on the final weight and assay. Voyage to China is roughly 3–4 weeks.", "Seller and buyer", "Final invoice + payment"],
   ["11.4", "11. Documents and payment", ["bulk", "container", "road"], "Export money brought back to SA", "The seller's bank reports the inflow and the Reserve Bank matches it to the export declaration.", "Seller", "Bank's report"],
   ["11.5", "11. Documents and payment", ["local", "bulk", "container", "road"], "Seller confirms in writing that it has been paid", "This is the trigger for our commission.", "Seller", "Written confirmation or escrow release"],
   ["12.1", "12. Commission and close", ["local", "bulk", "container", "road"], "Commission invoiced on paid and delivered DMT", "Attach the final certificate of weight or weighbridge summary and the seller's proof of receipt. Charge VAT only if we are VAT-registered (compulsory above R2.3m a year from 1 Apr 2026).", "Us", "Commission invoice"],
   ["12.2", "12. Commission and close", ["local", "bulk", "container", "road"], "Commission received", "Escrow split pays automatically; otherwise chase on the agreed day (e.g. 7 working days after the seller is paid). A commission claim expires after 3 years – invoice and demand promptly.", "Us", "Proof of payment"],
   ["12.3", "12. Commission and close", ["local", "bulk", "container", "road"], "Repeat orders logged against the non-circumvention period", "Every later order between the same parties earns commission under the agreement.", "Us", "Deal log"]
  ],
  "transport": [
   ["t1.1", "1. Qualify", ["local", "bulk", "container", "road"], "Client and receiver identified (who pays, who receives)", "Company names and CIPC numbers, the person who signs and the person who pays. Phone the receiver directly to confirm the loads are real.", "Us", "Names and numbers in Deal terms"],
   ["t1.2", "1. Qualify", ["local", "bulk", "container", "road"], "Cargo, route, volumes and loading hours in writing", "Cargo, pickup and drop-off addresses, km, tonnes per load, loads per day/week/month, loading and offloading hours, waiting-time rules. Contradicting figures are sorted out before pricing.", "Us, with the client side", "Written confirmation"],
   ["t1.3", "1. Qualify", ["local", "bulk", "container", "road"], "Transporter lined up with the right trucks", "Truck type (e.g. 34 t side tippers), how many, and from what date.", "Us, with the transporter", "Written availability"],
   ["t2.1", "2. Paperwork", ["local", "bulk", "container", "road"], "NCNDA / non-circumvention signed", "Signed by the client side and the transporter so nobody goes around us. SA law; e-signature is valid.", "Us, client side, transporter", "Signed NCNDA in Files"],
   ["t2.2", "2. Paperwork", ["local", "bulk", "container", "road"], "Split per ton agreed in writing (who gets what)", "Every party's cut per ton written down, with VAT stated, so our margin is clear.", "Us and the other intermediaries", "Written split"],
   ["t3.1", "3. Terms", ["local", "bulk", "container", "road"], "Client rate agreed, VAT in or out stated", "Rate per ton, per load or per km; VAT included or excluded in writing; which weighbridge sets the tonnes (loading or offloading).", "Client side", "Rate confirmation"],
   ["t3.2", "3. Terms", ["local", "bulk", "container", "road"], "Payment terms agreed in writing", "E.g. paid X days from the signed POD (proof of delivery). '50/50' must be spelled out: 50% when, and 50% when. Who invoices whom.", "Client side", "Written payment terms"],
   ["t3.3", "3. Terms", ["local", "bulk", "container", "road"], "Transporter rate and inclusions agreed (diesel, payload)", "Rate, payload per truck, diesel arrangement, tolls, waiting time and demurrage.", "Transporter", "Rate confirmation"],
   ["t3.4", "3. Terms", ["local", "bulk", "container", "road"], "Permits and special requirements answered", "Any permits, bonded store or RIB questions answered in writing before loading.", "Client side", "Written answer"],
   ["t4.1", "4. Checks", ["local", "bulk", "container", "road"], "Counterparty checks done (CIPC, Truecaller, call the receiver)", "Company active on CIPC, directors match, numbers belong to who they say, the receiver confirms.", "Us", "Check notes"],
   ["t4.2", "4. Checks", ["local", "bulk", "container", "road"], "Transporter checked: GIT insurance, trucks, drivers", "Goods-in-transit cover certificate with an amount that matches the cargo value, vehicle licences and roadworthies, driver licences and PrDP, tracking.", "Transporter", "Insurance certificate + vehicle list"],
   ["t5.1", "5. Agreements", ["local", "bulk", "container", "road"], "Written agreement signed with the client side", "Rates, VAT, payment days from POD, which weighbridge counts, loading windows, liability and claims, our commission.", "Client side", "Signed agreement"],
   ["t5.2", "5. Agreements", ["local", "bulk", "container", "road"], "Written agreement signed with the transporter", "Rate, trucks, payload, GIT cover, POD and weighbridge rules, payment days, non-circumvention.", "Transporter", "Signed agreement"],
   ["t6.1", "6. Trial load", ["local", "bulk", "container", "road"], "Trial load delivered with POD and weighbridge tickets", "Signed POD and weighbridge tickets at both ends.", "Transporter", "POD + tickets in Files"],
   ["t6.2", "6. Trial load", ["local", "bulk", "container", "road"], "Trial load paid", "Paid on the agreed terms before scaling up.", "Client side", "Proof of payment"],
   ["t7.1", "7. Running", ["local", "bulk", "container", "road"], "Truck packs / tracker access shared (only after 5 and 6)", "Do not hand over truck packs, spreadsheets or tracker logins until the agreements are signed and the trial is paid.", "Us", "Note"],
   ["t7.2", "7. Running", ["local", "bulk", "container", "road"], "Regular loads running; POD and tickets filed per load", "Keep every POD and weighbridge ticket – payment runs from them.", "Transporter", "Load log"],
   ["t8.1", "8. Close-out", ["local", "bulk", "container", "road"], "Invoices paid", "Chase on the agreed day from each POD.", "Client side", "Proof of payment"],
   ["t8.2", "8. Close-out", ["local", "bulk", "container", "road"], "Our margin received", "Paid per the written split.", "Us", "Proof of payment"]
  ]
 }
};
