#!/usr/bin/env python3
"""Walk through everyday jobs in demo mode (iPhone 8 size) and print PASS / FAIL for each.

Usage:  python3 tools/flows.py
Same set-up as tools/screens.py: a temporary copy of the app on 127.0.0.1:8793, index.html?demo
(fictional data, nothing saved). If the supabase-js CDN is blocked, set SUPABASE_JS=/path/to/supabase.js.
Add a check here whenever a job changes.
"""
import asyncio, subprocess, time, os, sys, shutil, tempfile
from playwright.async_api import async_playwright
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LIB = os.environ.get("SUPABASE_JS")
CDN='<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>'
res=[]
def check(name, ok, info=""): res.append(("PASS" if ok else "FAIL", name, info))
async def main():
    d=tempfile.mkdtemp()
    for n in os.listdir(REPO):
        p=os.path.join(REPO,n)
        if os.path.isfile(p): shutil.copy(p,d)
    if LIB:
        shutil.copy(LIB,os.path.join(d,"supabase.local.js")); h=open(os.path.join(d,"index.html"),encoding="utf-8").read().replace(CDN,'<script src="supabase.local.js"></script>'); open(os.path.join(d,"index.html"),"w",encoding="utf-8").write(h)
    srv=subprocess.Popen([sys.executable,"-m","http.server","8793","--bind","127.0.0.1"],cwd=d,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(0.8)
    errs=[]
    try:
        async with async_playwright() as p:
            b=await p.chromium.launch(); ctx=await b.new_context(viewport={"width":375,"height":667},is_mobile=True,has_touch=True,service_workers="block")
            pg=await ctx.new_page(); pg.on("pageerror",lambda e: errs.append(str(e)))
            pg.on("dialog", lambda dd: asyncio.ensure_future(dd.dismiss()))
            U="http://127.0.0.1:8793/index.html?demo"
            await pg.goto(U,wait_until="networkidle"); await pg.evaluate("()=>{try{localStorage.clear()}catch(e){}}"); await pg.goto(U,wait_until="networkidle"); await pg.wait_for_timeout(400)
            ev=pg.evaluate; W=lambda ms=300: pg.wait_for_timeout(ms)
            taps=0
            async def tap(sel):
                nonlocal taps; await pg.locator(sel).first.click(); taps+=1; await W()
            # 1 Accept all
            n0=await ev("window._items.filter(i=>i.state==='Proposed' && (i.owner||'Chris')==='Chris').length")
            await tap("button[data-qa=acceptall]")
            n1=await ev("window._items.filter(i=>i.state==='Proposed' && (i.owner||'Chris')==='Chris').length")
            check("Accept all confirms Chris's suggestions", n0>0 and n1==0, f"{n0}->{n1}")
            # 2 open a task, Back closes the sheet
            await tap(".hlist .hrow .hr-main"); s1=await pg.locator(".isheet").count()
            await pg.go_back(); await W(); s2=await pg.locator(".isheet").count()
            check("Task sheet opens and phone Back closes it", s1==1 and s2==0)
            # 3 new task for Annemarie due tomorrow
            taps=0
            await tap("#plusBtn"); await tap("button[data-add=task]")
            await pg.fill("#tsWhat","Send the truck list"); await tap("[data-towner=Annemarie]"); await tap("[data-tdue='1']"); await tap("#tsAdd")
            added=await ev("window._items.find(i=>i.waiting_for==='Send the truck list')")
            check("New task: Our job for Annemarie due tomorrow in <=5 taps", bool(added) and added['owner']=='Annemarie' and added['due_on'] and taps<=5, f"taps={taps} due={added and added['due_on']}")
            await tap("[data-who=Annemarie]")
            txt=await ev("[...document.querySelectorAll('.hcard')].map(g=>g.innerText).join(' | ')")
            check("It shows under Tomorrow on Annemarie's list", "Tomorrow" in txt and "Send the truck list" in txt.split("Tomorrow")[1])
            await tap("[data-who=Chris]")
            # 4 deal page and tick next step
            taps=0
            await tap(".tabs button[data-v=deals]"); await tap(".dcard")
            title=await ev("document.getElementById('pageTitle').textContent")
            nid=await ev("(()=>{const d=dealById(dealPage); const pg=dealProgress(d.id); return pg.next && pg.next.id})()")
            await tap(f"[data-step='{nid}']"); await tap(f"button[data-setstep='{nid}'][data-v=done]")
            st=await ev(f"(window._steps.find(s=>s.id==='{nid}')||{{}}).status")
            check("Deal opens as its own page and next step ticks in <=4 taps", st=="done" and taps<=4 and "Deals"!=title, f"title={title} taps={taps} status={st}")
            for t in ["numbers","notes","steps"]:
                await ev(f"[...document.querySelectorAll('[data-dtab]')].find(x=>x.dataset.dtab.endsWith(':{t}')).click()"); await W(200)
            tabs=await ev("[...document.querySelectorAll('.dtabs4 .dtab')].map(b=>{const r=b.getBoundingClientRect(); return r.right<=innerWidth && r.left>=0}).every(Boolean)")
            check("All deal tabs visible without sideways scroll", tabs)
            await pg.go_back(); await W(); v=await ev("view")
            check("Back from a deal page returns to the deals list", v=="deals", v)
            # 5 contacts search
            await tap(".tabs button[data-v=leads]")
            await pg.fill("#dQ","Lee"); await W(700)
            t=await ev("document.getElementById('list').innerText")
            check("Contacts: search is first and finds the person we wait on", "Sam & Lee" in t, "")
            await ev("setDirSeg('saved'); render()"); await W()
            t=await ev("document.getElementById('list').innerText")
            check("Contacts: Saved contacts shows the saved card", "Lee (demo)" in t)
            await pg.fill("#dQ",""); await W(500)
            # 6 chat picker
            await tap("#plusBtn"); await tap("button[data-add=chat]")
            await pg.fill("#pkQ","Lee"); await W()
            await tap("#pkRes [data-pick]")
            cs=await ev("!document.getElementById('chatSheet').classList.contains('hidden') && document.getElementById('csFor').textContent")
            check("WhatsApp chat: 'Whose chat?' picker opens the import sheet for that person", bool(cs) and "Lee" in cs, str(cs))
            await pg.go_back(); await W(); c2=await ev("document.getElementById('chatSheet').classList.contains('hidden')")
            check("Back closes the chat sheet", c2)
            # 7 typing mode on the board
            await tap(".tabs button[data-v=board]"); await pg.focus("#cText"); await W(300)
            nokb=await ev("getComputedStyle(document.querySelector('.tabs')).display!=='none'")
            await ev("Object.defineProperty(window,'innerHeight',{value:667,configurable:true}); Object.defineProperty(window,'visualViewport',{value:{height:380,addEventListener(){}},configurable:true}); updTyping()")
            hid=await ev("getComputedStyle(document.querySelector('.tabs')).display==='none'")
            await ev("Object.defineProperty(window,'visualViewport',{value:{height:667,addEventListener(){}},configurable:true}); updTyping()")
            back=await ev("getComputedStyle(document.querySelector('.tabs')).display!=='none'")
            await pg.evaluate("document.activeElement.blur()"); await W(300)
            check("Bottom bar hides only while the keyboard is open", nokb and hid and back, f"{nokb} {hid} {back}")
            # 8 More -> Settings theme toggle, Guides
            await tap("#menuBtn"); await tap("button[data-mview=settings]")
            th0=await ev("document.documentElement.dataset.theme"); await tap("button[data-set=theme]"); th1=await ev("document.documentElement.dataset.theme")
            check("Settings switches light/dark", th0!=th1, f"{th0}->{th1}")
            await tap("#menuBtn"); await tap("button[data-mview=guides]")
            g=await ev("document.getElementById('list').innerText.length")
            check("Guides page shows the playbook", g>200, str(g))
            # 9 due date on a task
            await ev("goView('worklist')"); await W()
            await ev("openItemSheet('2')"); await W()
            await ev("document.querySelector('.isheet .dr-b button[data-v]').click()"); await W()
            du=await ev("window._items.find(i=>i.id==='2').due_on")
            check("Due date can be set from the task sheet", bool(du), str(du))
            # ---- step 1 (v17): easy guides, + New deal, calculators, Speak, voice note, checks ----
            # 10 "+ New deal" from inside the new-task form keeps the form and picks the new deal
            await ev("window._sheetItem=null; goView('worklist')"); await W()
            await tap("#plusBtn"); await tap("button[data-add=task]"); await pg.fill("#tsWhat", "Book the trucks")
            await ev("document.querySelector('#taskSheet .tsmore').open = true"); await W(200)
            await pg.select_option("#tsDeal", "__newdeal"); await W()
            both=await ev("!document.getElementById('ndSheet').classList.contains('hidden') && !document.getElementById('taskSheet').classList.contains('hidden')")
            await pg.fill("#ndsName", "Maize – Example farm → Example mill"); await tap("[data-secp=nds] [data-secpick=Transport]"); await tap("#ndsAdd")
            nd=await ev("(() => { const d = (window._deals||[]).find(x => x.name === 'Maize – Example farm → Example mill'); return { id: d && d.id, kind: d && d.kind, area: d && d.area, sel: document.getElementById('tsDeal').value, what: document.getElementById('tsWhat').value, open: !document.getElementById('taskSheet').classList.contains('hidden'), nd: document.getElementById('ndSheet').classList.contains('hidden') }; })()")
            check("+ New deal from the task form: small sheet on top, Section Transport gives a transport deal, it is picked, typed text kept", both and nd['id'] and nd['kind']=="transport" and nd['area']=="Transport" and nd['sel']==nd['id'] and nd['what']=="Book the trucks" and nd['open'] and nd['nd'], str(nd))
            await tap("#tsClose")
            # 11 "+ New deal" in a task's own deal list does not unlink the task, and phone Back closes only the small sheet
            await ev("openItemSheet('2')"); await W()
            d0=await ev("window._items.find(i=>i.id==='2').deal_id")
            await pg.select_option(".isheet select[data-dealsel]", "__newdeal"); await W()
            d1=await ev("window._items.find(i=>i.id==='2').deal_id"); o1=await ev("!document.getElementById('ndSheet').classList.contains('hidden')")
            await pg.go_back(); await W()
            o2=await ev("document.getElementById('ndSheet').classList.contains('hidden') && !!document.querySelector('.isheet')")
            check("+ New deal in a task's deal list keeps its deal; Back closes only the New deal sheet", d0==d1 and o1 and o2, f"{d0}->{d1} {o1} {o2}")
            await ev("window._sheetItem=null; render()"); await W()
            # 12 everyday calculator
            await ev("goView('calc')"); await W(); await tap("button[data-calctab=everyday]")
            async def keys(seq):
                for k in seq: await ev(f"document.querySelector('button[data-ek=\"{k}\"]').click()"); await W(60)
                return await ev("document.getElementById('ecVal').textContent")
            v1=await keys(["C","1","2","0","0","+VAT"]); v2=await keys(["C","2","+","3","×","4","="]); v3=await keys(["C","1","0","0","÷","0","="]); v4=await keys(["C","1","1","5","0","-VAT"])
            check("Everyday calculator: 1200 + VAT, 2+3×4, divide by 0, remove VAT", v1.replace("\u00a0"," ")=="1 380" and v2=="14" and "divide" in v3 and v4.replace("\u00a0"," ")=="1 000", f"{v1} | {v2} | {v3} | {v4}")
            # 13 transport calculator: kilometres to money
            await tap("button[data-calctab=transport]")
            for k,v in [("km","169"),("rkm","28"),("toll","450"),("client","350"),("loads","20")]:
                await pg.fill(f"input[data-tr={k}]", v)
            r=await ev("document.getElementById('trRes').innerText.replace(/\u00a0/g,' ')")
            check("Transport calculator: 169 km at R28/km + R450 tolls, client R350/t", "R 9 914" in r and "R 292 a ton" in r and "R 58 a ton" in r and "R 39 720" in r, r.replace("\n"," | ")[:200])
            top=await ev("document.getElementById('trTop').innerText.replace(/\u00a0/g,' ')")
            await tap("button[data-trret=No]")
            r2=await ev("document.getElementById('trRes').innerText.replace(/\u00a0/g,' ')"); top2=await ev("document.getElementById('trTop').innerText.replace(/\u00a0/g,' ')")
            nsel=await ev("document.querySelectorAll('.trc select').length")
            check("Transport: answer on top, One way only halves the km, no drop-down lists", "R 292 a ton" in top and "R 39 720" in top and "169 km (one way)" in r2 and "R 152 a ton" in top2 and nsel==0, f"{top.replace(chr(10),' | ')} || {top2.replace(chr(10),' | ')} || selects {nsel}")
            await tap("button[data-trret=Yes]")
            await tap("button[data-calctab=chrome]"); ch=await ev("!!document.getElementById('calcDealSel')")
            check("Chrome and ore calculator is its own tab", ch)
            # 14 guides read as short points
            await ev("openKeys.add('+lib:kit'); goView('guides')"); await W()
            await ev("document.querySelector('#lib-kit .libi').open = true"); await W()
            ez=await ev("({ steps: document.querySelectorAll('#lib-kit .easy .ez-step').length, pts: document.querySelectorAll('#lib-kit .easy li').length, kitTwice: document.querySelectorAll('#kitlib').length })")
            check("Guides: numbered stages with short points, deal kit shown once", ez['steps']>=3 and ez['pts']>=5 and ez['kitTwice']==0, str(ez))
            # 15 step details as points, and opening a step does not pop up the keyboard
            await ev("goTo('deal:dm1')"); await W()
            nid=await ev("dealProgress('dm1').next.id"); await tap(f"[data-step='{nid}']")
            sd=await ev("({ pts: document.querySelectorAll('.step-p .sd .easy li, .step-p .sd .easy .ez-p').length, focus: document.activeElement && document.activeElement.tagName })")
            check("Step details read as points; opening a step does not focus a text box", sd['pts']>=1 and sd['focus'] not in ("INPUT","TEXTAREA"), str(sd))
            # 16 voice note
            await tap("#plusBtn"); await tap("button[data-add=voice]")
            vn=await ev("({ open: !document.getElementById('vnSheet').classList.contains('hidden'), speak: !!document.querySelector('#vnSheet .bigmic'), rec: !!document.getElementById('vnRecBtn') })")
            await pg.fill("#vnText", "Call the mill about Tuesday"); await tap("#vnSave")
            vc=await ev("document.getElementById('vnSheet').classList.contains('hidden')")
            check("+ › Voice note: Speak, type, Save closes the sheet", vn['open'] and vn['speak'] and vn['rec'] and vc, str(vn))
            await tap("#plusBtn"); await tap("button[data-add=voice]"); await pg.go_back(); await W()
            check("Back closes the voice-note sheet", await ev("document.getElementById('vnSheet').classList.contains('hidden')"))
            # 17 Speak buttons beside the text boxes
            await ev("openTaskSheet()"); await W()
            m1=await ev("!!document.querySelector('#taskSheet .micwrap #tsWhat') && !!document.querySelector('#taskSheet button[data-mic=\"#tsWhat\"]')"); await tap("#tsClose")
            await ev("goView('board')"); await W(); m2=await ev("!!document.querySelector('#composer button[data-mic=\"#cText\"]') && document.getElementById('cText').getBoundingClientRect().width > 250")
            await ev("goView('bot')"); await W(); m3=await ev("!!document.querySelector('button[data-mic=\"#q\"]')")
            check("Speak button beside the task, board and bot boxes (board box keeps full width)", m1 and m2 and m3, f"{m1} {m2} {m3}")
            # 18 checks on a saved contact and on a lead
            await ev("setDirSeg('saved'); goView('leads')"); await W()
            await tap(".ccard button[data-checks]")
            ck=await ev("({ open: !document.getElementById('ckSheet').classList.contains('hidden'), links: document.querySelectorAll('#ckBody a.pkrow').length, res: document.querySelectorAll('#ckBody [data-ckres]').length })")
            await tap("#ckBody [data-ckres]")
            cc=await ev("document.getElementById('ckSheet').classList.contains('hidden') && document.getElementById('toast').textContent")
            check("Checks: sheet with 5 free look-ups; the result saves a note (demo) and closes", ck['open'] and ck['links']==5 and ck['res']==2 and bool(cc), str(ck) + " " + str(cc))
            # ---- step 2 (v17): the reader – WhatsApp quote, photo or PDF, voice note (demo answers; the real reader needs a login) ----
            await ev("document.getElementById('ckSheet').classList.add('hidden'); goView('worklist')"); await W()
            n0=await ev("window._items.length")
            await tap("#plusBtn"); await tap("button[data-add=quote]")
            await pg.fill("#rdText", "Hi Chris, chrome conc 40-42% 5000t/month R2400/t FOT plant Rustenburg. Trucks from Monday.")
            await tap("#rdGo"); await W(700)
            rv=await ev("({ open: !document.getElementById('rvSheet').classList.contains('hidden'), card: !!document.querySelector('#rvBody .rvq'), missing: document.querySelectorAll('#rvBody .rvmiss li').length, ticked: document.querySelectorAll('#rvBody [data-rv^=\"task:\"]:checked').length })")
            await tap("#rvSave"); await W(400)
            n1=await ev("window._items.length"); closed=await ev("document.getElementById('rvSheet').classList.contains('hidden')")
            check("Decode a WhatsApp quote: tidy card, what is missing, tasks ticked, Save adds them", rv['open'] and rv['card'] and rv['missing']>=3 and rv['ticked']==2 and n1==n0+2 and closed, f"{rv} items {n0}->{n1}")
            png=__import__("base64").b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==")
            await tap("#plusBtn"); await tap("button[data-add=read]")
            await pg.set_input_files("#rdCamInput", files=[{"name": "notes.png", "mimeType": "image/png", "buffer": png}]); await W(500)
            img=await ev("!!document.querySelector('#rdPreview img')")
            await tap("#rdGo"); await W(700)
            rp=await ev("({ tasks: document.querySelectorAll('#rvBody [data-rv^=\"task:\"]').length, contacts: document.querySelectorAll('#rvBody [data-rv^=\"contact:\"]').length, terms: document.querySelectorAll('#rvBody [data-rv^=\"term:\"]').length })")
            await ev("document.querySelector('#rvBody [data-rv=\"contact:0\"]').checked = false; document.querySelector('#rvBody [data-rvf=\"task:0:what\"]').value = 'Book the site visit for Tuesday'")
            await ev("const s = document.getElementById('rvTermDeal'); s.value = 'dm1'; s.dispatchEvent(new Event('change', { bubbles: true }))"); await W(200)
            tt=await ev("document.querySelectorAll('#rvBody [data-rv^=\"term:\"]:checked').length")
            await tap("#rvSave"); await W(400)
            fixed=await ev("!!window._items.find(i => i.waiting_for === 'Book the site visit for Tuesday')"); pr=await ev("JSON.stringify(dealById('dm1').params)")
            check("Read a photo: preview, review with fixable words, untick a contact, terms go on the chosen deal", img and rp['tasks']==2 and rp['contacts']==1 and rp['terms']==3 and fixed and "40–42" in pr and "private" not in pr, f"{rp} ticked terms {tt} params {pr[:120]}")
            await ev("openVoiceNote()"); await W(); await pg.fill("#vnText", "Send the truck list today and chase Pat for the NCNDA tomorrow")
            n2=await ev("window._items.length"); await tap("#vnTasks"); await W(700)
            vo=await ev("!document.getElementById('rvSheet').classList.contains('hidden') && document.getElementById('vnSheet').classList.contains('hidden')")
            await tap("#rvSave"); await W(400); n3=await ev("window._items.length")
            check("Voice note › Make tasks from it: review sheet, then the ticked tasks are added", vo and n3==n2+2, f"{vo} {n2}->{n3}")
            await ev("goTo('deal:dm1')"); await W()
            await ev("[...document.querySelectorAll('[data-dtab]')].find(x=>x.dataset.dtab.endsWith(':numbers')).click()"); await W()
            await tap("button[data-readdeal]")
            rd=await ev("({ open: !document.getElementById('rdSheet').classList.contains('hidden'), doc: document.querySelector('[data-rdwhat=doc]').classList.contains('on'), about: document.getElementById('rdAbout').value })")
            check("Deal › Numbers › Read terms from a document opens the reader set to this deal", rd['open'] and rd['doc'] and rd['about']=="deal:dm1", str(rd))
            await pg.go_back(); await W()
            check("Back closes the reader", await ev("document.getElementById('rdSheet').classList.contains('hidden')"))
            # palette: Titanium by default; Settings can switch to Velvet and back
            p0=await ev("document.documentElement.dataset.palette")
            await ev("goView('settings')"); await W()
            await tap("button[data-set=palette][data-v=velvet]"); p1=await ev("document.documentElement.dataset.palette + '|' + getComputedStyle(document.documentElement).getPropertyValue('--primary').trim()")
            await tap("button[data-set=palette][data-v=titanium]"); p2=await ev("document.documentElement.dataset.palette + '|' + getComputedStyle(document.documentElement).getPropertyValue('--primary').trim()")
            check("Colours: Titanium by default, Settings switches to Velvet and back", p0=="titanium" and p1.startswith("velvet|") and p2.startswith("titanium|") and p1.split("|")[1]!=p2.split("|")[1], f"{p0} {p1} {p2}")
            # Home v2: four tiles; tap one to see only those, tap again for everything
            await ev("goView('worklist'); window.scrollTo(0,0)"); await W()
            nt=await ev("document.querySelectorAll('.htiles .htile').length")
            await tap("button[data-hf=urgent]")
            fu1=await ev("({ rows: document.querySelectorAll('.hlist .hrow').length, notUrgent: [...document.querySelectorAll('.hlist .hrow')].filter(r => !/Urgent/.test(r.innerText)).length, deals: !!document.querySelector('.hcard.t-deal'), pressed: document.querySelector('button[data-hf=urgent]').getAttribute('aria-pressed') })")
            await tap("button[data-hf=urgent]")
            fu2=await ev("({ deals: !!document.querySelector('.hcard.t-deal'), filt: document.querySelectorAll('.htile.on').length })")
            check("Home: four tiles; Urgent shows only urgent tasks, tap again shows everything", nt==4 and fu1['rows']>=1 and fu1['notUrgent']==0 and not fu1['deals'] and fu1['pressed']=="true" and fu2['deals'] and fu2['filt']==0, f"{nt} {fu1} {fu2}")
            # buyer-search step: No reply yet -> Follow up keeps it open, dated, and it shows on Today (not as done)
            await ev("goTo('task:t2')"); await W(500)
            fd=await ev("document.getElementById('tFu') ? document.getElementById('tFu').value : ''")
            await tap("button[data-dtaskact=t2][data-v=followup]"); await W()
            tk=await ev("JSON.stringify((({status, not_before, outcome}) => ({status, not_before, outcome}))(window._ltasks.find(t => t.id === 't2')))")
            await ev("goView('worklist'); window.scrollTo(0,0)"); await W()
            onToday=await ev("({ row: !!document.querySelector('.hlist [data-tgo=\"task:t2\"]'), inBuyer: !!document.querySelector('.hcard.t-buyer [data-tgo=\"lead:l1\"]'), text: (document.querySelector('.hlist [data-tgo=\"task:t2\"]') || {}).innerText || '' })")
            check("Buyer step: Follow up keeps it open with a date (from 'by 29 Sep' in the step) and puts it on Today", fd > await ev("todaySA()") and '"status":"open"' in tk and f'"not_before":"{fd}"' in tk and "No reply yet" in tk and onToday['row'] and not onToday['inBuyer'] and "Follow up" in onToday['text'], f"date {fd} {tk} {onToday}")
            await tap("[data-tgo=\"task:t2\"]"); await W(500)
            back=await ev("({ view: view, form: !!document.querySelector('.tdone'), btn: !!document.querySelector('button[data-dtaskact=t2][data-v=followup]') })")
            check("Tapping a follow-up on Today opens the step with Done / Follow up", back['view']=="leads" and back['form'] and back['btn'], str(back))
            # Sections: one switch on Today, Deals, Contacts and Board; Chrome shows only chrome work; a new section can be added
            bars={}
            for v in ["worklist","deals","leads","board"]:
                await ev(f"goView('{v}'); window.scrollTo(0,0)"); await W(200)
                bars[v]=await ev("[...document.querySelectorAll('.secbar button')].map(b=>b.dataset.sec).join(',')")
            await ev("goView('worklist'); window.scrollTo(0,0)"); await W()
            await tap(".secbar button[data-sec=Chrome]")
            sc=await ev("(() => { const ids=[...document.querySelectorAll('.hlist [data-tgo^=\"item:\"]')].map(b=>b.dataset.tgo.slice(5)); const its=ids.map(id=>window._items.find(i=>i.id===id)).filter(Boolean); return { n: its.length, notChrome: its.filter(i=>!secsOfItem(i).includes('Chrome')).length, saved: localStorage.getItem('section') }; })()")
            await ev("goView('deals')"); await W()
            dc=await ev("[...document.querySelectorAll('.deal.srail .dn')].map(x=>x.textContent).join(' | ')")
            await tap(".secbar button[data-sec=All]")
            check("Sections: switch on Today, Deals, Contacts and Board; Chrome shows only chrome tasks and deals, remembered", all(b=="All,Chrome,Manganese,Transport" for b in bars.values()) and sc['n']>=1 and sc['notChrome']==0 and sc['saved']=="Chrome" and "Chrome" in dc and "Maize" not in dc, f"{bars} {sc} deals: {dc}")
            await ev("goView('worklist')"); await W()
            await tap("#plusBtn"); await tap("button[data-add=task]"); await ev("document.querySelector('#taskSheet .tsmore').open = true"); await W(200)
            await pg.select_option("#tsDeal", "__newdeal"); await W()
            await pg.fill("#ndsName", "Coal – Example colliery → Example buyer"); await tap("[data-secp=nds] [data-secpick='+']")
            await pg.fill("#ndsSecName", "Coal"); await tap("#ndsAdd"); await W()
            cd=await ev("(() => { const d=(window._deals||[]).find(x=>x.name.startsWith('Coal –')); return { area: d&&d.area, kind: d&&d.kind, secs: sectionsList().join(',') }; })()")
            await tap("#tsClose"); await ev("goView('deals')"); await W()
            cbar=await ev("[...document.querySelectorAll('.secbar button')].map(b=>b.dataset.sec).join(',')")
            check("Add a section: a new deal in section Coal (mineral checklist) makes Coal appear in the switch", cd['area']=="Coal" and cd['kind']=="mineral" and "Coal" in cbar, f"{cd} bar {cbar}")
            await b.close()
    finally: srv.terminate(); shutil.rmtree(d,ignore_errors=True)
    for r in res: print(*r)
    print("PAGE ERRORS:", errs or "none")
asyncio.run(main())
